tienda/sitio/urls.py
from django.urls import path, include
from . import views

app_name = "sitio"
urlpatterns = [
    path('', views.index, name="index"),
    #
    path('filtro_categorias/<int:categoria_id>', views.filtro_categorias, name="filtro_categorias"),
    path('filtro_productos', views.filtro_productos, name="filtro_productos"),    
    #   
    path('<int:producto_id>', views.producto, name="producto"),
    #
    path('producto_alta', views.producto_alta, name="producto_alta"),
    #
    path('producto_editar/<int:producto_id>', views.producto_editar, name="producto_editar"),
    path('producto_eliminar/<int:producto_id>', views.producto_eliminar, name="producto_eliminar"),
    #
    path('carrito/<int:producto_id>', views.carrito, name="carrito"),
    path('consultar_carrito', views.consultar_carrito, name="consultar_carrito"),
    #
    #path('carrito_quitar/<int:producto_id', views.carrito_quitar, name="carrito_quitar"),

    path('carrito_quitar', views.carrito_quitar, name="carrito_quitar"),
    path('carrito_eliminar', views.carrito_eliminar, name="carrito_eliminar"),
    #
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('envia_correo', views.envia_correo, name="envia_correo"),
 
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("sitio.urls")),
    path('sitio/', include("sitio.urls")),
    path('registrarse/', include('usuarios.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

tienda/usuarios/urls.py
from django.urls import path, include
from . import views

app_name = "usuarios"
urlpatterns = [
    path('', views.registrarse, name="registrarse"),
]

tienda/sitio/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.

""""""
class Seccion(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.descripcion}"

class Articulo(models.Model):
    seccion = models.ForeignKey(Seccion, on_delete=models.CASCADE, related_name="clasificacion_seccion")
    fecha_publicacion = models.DateField(null= False)
    titulo = models.CharField(max_length=250, null=False)
    contenido = models.CharField(max_length=2000, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    publicador = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publicador")

    def __str__(self):
        return f"{self.fecha_publicacion} - {self.titulo} ({self.publicador})"

"""class LeerMasTarde(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    publicaciones = models.ManyToManyField(Articulo) 

    def __str__(self):
        return f"{self.usuario} - {self.publicaciones}" """  

class Categoria(models.Model):
    descripcion = models.CharField(max_length=64, null=False)

    def __str__(self):
        return f"{self.descripcion}"

class Producto(models.Model):
    titulo = models.CharField(max_length=128, null=False)
    imagen = models.FileField(upload_to='imagenes/')
    descripcion = models.CharField(max_length=1000, null=False)
    precio = models.FloatField(null=False)                       # models.DecimalField(..., max_digits=5, decimal_places=2) models.FloatField
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="clasificacion_categoria")

    #def __str__(self):
        #return f"{self.categoria} - {self.titulo}"
        #return f"{self.categoria} - {self.titulo} ({self.precio})"

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="usuario")
    listado_productos = models.ManyToManyField(Producto)
    #publicaciones = models.ManyToManyField(Articulo)
    #vuelos = models.ManyToManyField(Vuelo, blank=True, related_name="pasajeros")
    total_carrito = models.FloatField(null=False)

    def __str__(self):
        return f"{self.usuario} {self.listado_productos}"

tienda/sitio/forms.py
from django import forms
from .models import Producto

class FormProducto(forms.ModelForm):
    #campos del modelo
    class Meta:
        model = Producto
        fields = ('categoria',  'titulo', 'descripcion', 'imagen', 'precio')
        widgets = {
            #'fecha_publicacion': forms.SelectDateWidget(attrs={'class': 'pub_fecha_publicacion'}),
            'titulo': forms.TextInput(attrs={'class': 'pub_titulo'}),
            'descripcion': forms.Textarea(attrs={'class': 'pub_descripcion'}),
            'imagen': forms.FileInput(attrs={'name':'imagen_adjunta', 'class': 'pub_imagen'}),
        }

tienda/sitio/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from .forms import *
from .models import Producto, Categoria, Carrito
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.utils import timezone
from django.db.models import Q

# Create your views here.

# Reserved.objects.filter(client=client_id).order_by('check_in')
# Reserved.objects.filter(client=client_id).order_by('-check_in')
# Reserved.objects.filter(client=client_id).order_by('check_in')[::-1]
# Reserved.objects.all().filter(client=client_id).order_by('check_in').reverse()

# User.objects.all().order_by( class="hljs-comment">'-id')[:10]
# print(queryset)

def index(request):
    if "carrito" not in request.session:
        request.session["carrito"] = []
    print("request session carrito")
    print(request.session["carrito"]) 
    print(len(request.session["carrito"]))   
    return render(request,"tienda/index.html", {
        "productos_ppales": Producto.objects.all().order_by('-id')[0:3],
        "productos_sdarios": Producto.objects.all().order_by('-id')[3:10],
        #"lista_productos": Producto.objects.all().order_by('-id'),
        "lista_categorias": Categoria.objects.all(),
        "carrito": request.session["carrito"],
    })

def producto(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    return render(request, "tienda/articulo.html", {
        "producto": un_producto
    })

def about(request):
    return render(request,"tienda/about.html")

def contact(request):
    return render(request,"tienda/contact.html")

@login_required
def producto_alta(request):
    if request.method == "POST":
        #user = User.objects.get(username=request.user)
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen=request.FILES['imagen']))      
        if form.is_valid():
            form.save()
            return redirect("sitio:index")  # ERROR 
            #return HttpResponseRedirect(reverse("sitio:index")         
    else:
        form = FormProducto()
        return render(request, "tienda/producto_nuevo.html", {
            "form": form
        })

@login_required
def producto_editar(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    if request.method == "POST":  
        form = FormProducto(data=request.POST, files=request.FILES, instance=un_producto)
        if form.is_valid():
            form.save()
            return redirect("sitio:index")
    else:
        form = FormProducto(instance = un_producto)
        return render(request, 'tienda/producto_edicion.html', {
            "producto": un_producto,
            "form": form
        })

@login_required
def producto_eliminar(request, producto_id):
    un_producto = get_object_or_404(Producto, id=producto_id)
    un_producto.delete()
    return redirect("sitio:index")

def filtro_categorias(request, categoria_id):
    una_categoria = get_object_or_404(Categoria, id=categoria_id)
    queryset = Producto.objects.all()
    queryset = queryset.filter(categoria=una_categoria)
    return render(request,"tienda/busqueda.html", {
        "lista_productos": queryset,
        "lista_categorias": Categoria.objects.all(),
        "categoria_seleccionada": una_categoria
    })

def filtro_productos(request):
    if request.method == "GET":     
        una_busqueda = request.GET.get("busqueda")
        #print(una_busqueda)
        queryset = None 
        if una_busqueda:
            queryset = Producto.objects.filter(
                Q(titulo__icontains = una_busqueda) |
                Q(descripcion__icontains = una_busqueda)
            ).distinct()
        return render(request,"tienda/busqueda.html", {
            "lista_productos": queryset,
            "palabra_buscada": una_busqueda
        })   

@login_required
def carrito(request, producto_id):  # Agregar producto al carrito de compras
    un_producto = get_object_or_404(Producto, id=producto_id)
    for id in request.session["carrito"]:
        if id == producto_id:
            #print(producto_id)
            print("existe el producto!!")
            #existe el producto
            request.session["carrito"]             
            return HttpResponseRedirect(reverse("sitio:producto", args=(un_producto.id,))) 
        else:
            print("NO existe el producto")
                     
    request.session["carrito"] += [producto_id]

    return HttpResponseRedirect(reverse("sitio:producto", args=(un_producto.id,))) 

#lista.remove(elemento)
#lista.pop(posición)
#del lista[posicion]

@login_required
def carrito_quitar(request):
    producto_id = 10
    print ("producto_id en carrito_quitar")
    print (producto_id)
    return render(request,"tienda/actualiza_carrito.html", {
        "actual_carro": producto_id
    })

@login_required
def carrito_eliminar(request):  # Vaciar el carrito de compras
    producto_id = 10
    #un_producto = get_object_or_404(Producto, id=producto_id)
    print(len(request.session["carrito"]))
    print(len(request.session["carrito"]))
    while len(request.session["carrito"])>0:
        request.session["carrito"].pop()
        print("request session carrito se está vaciando")
    request.session.modified = True
    print(request.session["carrito"])
    #existe el producto
    return render(request,"tienda/elimina_carrito.html", {
        "elimi_carro": producto_id
    })
"""
def carrito_quitar(request, producto_id):  # Quitar producto al carrito de compras
    un_producto = get_object_or_404(Producto, id=producto_id)
    for id in request.session["carrito"]:
        if id == producto_id:
            print(producto_id)
            print("existe el producto!!")
            #existe el producto
            return HttpResponseRedirect(reverse("sitio:producto", args=(un_producto.id,)))
            #request.session["carrito"] += [producto_id] 
            #"request.session["carrito"].pop()"
            request.session["carrito"].remove(producto_id)
        else:
            print("NO existe el producto")
    return redirect("sitio:index")
    #return render(request,"tienda/consulta_carrito.html")                 
    #request.session["carrito"] += [producto_id]
    #return HttpResponseRedirect(reverse("sitio:producto", args=(un_producto.id,))) 
"""

@login_required
def consultar_carrito(request): #consultar productos agregados al carrito de compras por su ID y trae de la BD los demas campos a mostar
    miLista = []
    queryset = Producto.objects.all()
    for id in request.session["carrito"]:
        producto_id = id
        #-----------------------------------------------------
        un_producto = get_object_or_404(Producto, id=producto_id)
        queryset = Producto.objects.filter(id = producto_id)
        if queryset:
            for q in queryset:
                 print (q.titulo)
                 miLista.append((id, q.titulo, q.precio))
            #print(miLista)
        else:
            print("NO wxiste")
    return render(request,"tienda/consulta_carrito.html", {
        "carrito2": miLista,
        "consulta_carro": queryset
    })
        #-----------------------------------------------------

@login_required
def consulta_carrito(request): #consultar productos agregados al carrito de compras (solo los ID)
    if "carrito" not in request.session:
        request.session["carrito"] = []
    return render(request,"tienda/consulta_carrito.html", {
        "carrito": request.session["carrito"],
    })

def envia_correo(request):  # Vaciar el carrito de compras
    return render(request,"tienda/enviar_correo.html")

"""
print(Seller.objects.all().query)
SELECT "app_seller"."id", "app_seller"."name" FROM "app_seller"
"""   
"""
def reserva(request, vuelo_id):
    if request.method == "POST":
        vueloId = Vuelo.objects.get(pk=vuelo_id)
        pasajeroId = int(request.POST["pasajero"])
        unPasajero = Pasajero.objects.get(pk=pasajeroId)
        unPasajero.vuelos.add(vueloId)
        return HttpResponseRedirect(reverse("vuelo", args=(vuelo_id,)))
"""

tienda/sitio/templates/tienda/actualiza_carrito.html
{% extends "tienda/layout.html" %}

{% block content %}

<br>

<p> .... </p>

<br>
<br>

{% endblock %}

tienda/sitio/templates/tienda/articulo.html
{% extends "tienda/layout.html" %}
{% block content %}

	<!--<h2>ID:</h2>-->
	<br>
	<h3>{{ producto.id }}: {{ producto.titulo }}</h3>

	<div class="alert alert-info" role="alert">
		{{ producto.categoria }}
	</div>
	<br>
<!------
Imagen responsive
Bootstrap 4 incluye la clase .img-fluid para que las imágenes se adapten correctamente a los distintos dispositivos.
Ejemplo: < img src="eniun.jpg" class="img-fluid" alt="Eniun">
------->

	<!--- Imagen del Articulo centrado
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-xs-6 thumb">
				<img src="{{ media_url }}{{ producto.imagen.url }}" class="img-fluid" alt="Eniun" alt="{{ producto.imagen.name }}" />
			</div>
		</div>
	</div>
	--->

	<div class="container">
		<div class="row">
			
			<div class="col-lg-6 col-md-6 col-xs-6 thumb">
                <div>
                    <img src="{{ media_url }}{{ producto.imagen.url }}" class="img-fluid" alt="Eniun" alt="{{ producto.imagen.name }}"/>                            
                </div>

                <div class="d-flex flex-row-reverse">			
					<div class="p-6"></div>
				</div>

            </div>

            <div class="col-lg-6 col-md-6 col-xs-6 thumb">
                <div>
                	  <h4>{{ producto.categoria }}</h4>
                	  <h4>Descripción:</h4>
                     <p id="descripcion" font-size ="14px">{{ producto.descripcion |safe }}
					 </p>     
                </div>

                 {% if not user.is_authenticated %}                         
                <div class="d-flex">
					  <div class="p-2"><h4>Precio: {{ producto.precio }}</h4></div>
					  <div class="ml-auto p-2"><a href="{% url 'sitio:carrito' producto.id %}" class="btn btn-primary btn-sm" type="button">Agregar al Carrito</a></div>

				</div>
				 {% endif %} 

				 {% if user.is_authenticated %}    
				 		{% if perms.sitio.change_producto %}
				 			<div class="d-flex">
					 			<div class="ml-auto p-2">
									  		<a href="{% url 'sitio:producto_editar' producto.id %}" class="btn btn-primary btn-sm" type="button">Editar/Borrar</a>
								</div>
							</div>
						{% else %}	
							<div class="d-flex">
								<div class="ml-auto p-2">
								  		<a href="{% url 'sitio:carrito' producto.id %}" class="btn btn-primary btn-sm" type="button">Agregar al Carrito</a>
								 </div>
							</div>	 	
						{% endif %}	
				{% endif %} 			
            </div>

		</div>
	</div>

	<br>
	<br>
{% endblock %}

tienda/sitio/templates/tienda/articulo_edicion.html
{% extends "tienda/layout.html" %}
{% block content %}
<h3>Publicar un Articulo</h3>
<form enctype="multipart/form-data" action="{% url 'sitio:articulo_editar' articulo.id %}" method="post" >
    {% csrf_token %}
    <div class="form-group row">
        <label for="seccion_input"  class="col-sm-2 col-form-label">Seccion:</label> {{ form.seccion }} {{ form.seccion.errors }}
    </div>
    <div class="form-group row">
        <label for="titulo_input"  class="col-sm-2 col-form-label">Titulo:</label> {{ form.titulo }} {{ form.titulo.errors }}
    </div>
    <div class="form-group row">
        <label for="publicacion_input"  class="col-sm-2 col-form-label">Fecha de Publicacion:</label> {{ form.fecha_publicacion }} {{ form.fecha_publicacion.errors }}
    </div>
    <div class="form-group row">
        <label for="imagen_input"  class="col-sm-2 col-form-label">Imagen Adjunta:</label> {{ form.imagen }} {{ form.imagen.errors }}
    </div>
    <div class="form-group row"  class="col-sm-2 col-form-label">
        <label for="contenido_input">Contenido:</label> {{ form.contenido }} {{ form.contenido.errors }}
        <script>$("#id_contenido").removeAttr("required");</script>
    </div>
    <div class="col-auto">
        <a class="btn btn-secondary" href="{% url 'sitio:index'%}">Volver</a>
        <input type="submit" class="btn btn-primary" value="Editar">
    </div>
</form>
<a href="{% url 'sitio:index'%}">Volver</a>
{% endblock %}

tienda/sitio/templates/tienda/consulta_carrito.html
{% extends "tienda/layout.html" %}

{% block content %}

    <div class="col-12 text-center">
        <samp>
             <h2>CARRITO</h2>
        </samp>
    </div> 
        
    {% if user.is_authenticated %}      <!--usuario logueado--->
        <hr>                     
         <h3>{{ user.get_username }}</h3>
        <hr>

        {% if perms.sitio.add_producto %}

            <a href=""></a>
            <br>

        {% else %}  

            <!--<ol>
                { % for item in carrito2 % }
                    <li>{{item}}</li> 
                { % empty % }
                    <li>No hay productos en el Carrito.</li>
                { % endfor % }
            </ol>{ % unprod = 0 % }-->

            <ol>    
                {% for item in carrito2 %}

                    {% with item.0 as producto_id %} 
                    <!--{ { producto_id =  } }-->
                    <li>
                         Id_producto: {{producto_id}}: {{item.1}} -- {{item.2}} -- /<a href="{% url 'sitio:carrito_quitar' %}">Quitar</a> 
                    </li> <!--En python:  print(item[0],item[1], item[2])  -->
                    
                    {% endwith %}

                {% empty %}

                    <li>No hay productos en el Carrito.</li>

                {% endfor %}
                
            </ol>

            <div align="right">  <!----<button type="button" class="btn btn-outline-primary">Primary</button>-------boton btn-block py-2------>
                {% for item in carrito2 %}

                     <a href="{% url 'sitio:carrito_eliminar' %}" class="btn btn-primary btn-sm" type="button">Vaciar Carrito</a>
                     <a href="" class="btn btn-primary btn-sm" type="button">Finalizar Compra</a>
            
                {% empty %}

                    <a href="{% url 'sitio:carrito_eliminar' %}" class="btn btn-secondary btn-sm disabled"  type="button" aria-disabled="true">Vaciar Carrito</a>
                    <a href="" class="btn btn-secondary btn-sm disabled" type="button" aria-disabled="true">Finalizar Compra</a>

                {% endfor %}
            </div>

        {% endif %}     
         
    {% else %}
        <h3>...</h3>
    {% endif %} 

     <hr><br>
{% endblock %}

tienda/sitio/templates/tienda/elimina_carrito.html
{% extends "tienda/layout.html" %}

{% block content %}

<br>
<p> Tu carrito ha quedado vacío</p>
<br>
<a href="{% url 'sitio:consultar_carrito'%}">Regresar</a>

{% endblock %}

tienda/sitio/templates/tienda/enviar_correo.html
{% extends "registration/layout.html" %}

{% block content %}

<br>
<p> Gracias por comunicarse con nosotros a través de correo electrónico...

Muy pronto nos comunicaremos con usted.</p>
<br>
<br>

{% endblock %}

tienda/sitio/templates/tienda/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Jaguarete KAA. S.A.</title>
        
        <link rel="stylesheet" href="{% static 'estilos.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
       
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
        
        <script src="{% static 'scripts.js' %}"></script>

        <!--- iconos mini --->
        <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet"/>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"/>
        <!--- --->

        <!--- 
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>--->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
         <!--- <div class="text-center"> --->

    </head>
    <body>
        <div class="container bg-light">
            <header>
              
                <div id="bloque_login">

                    {% if user.is_authenticated %}      <!--usuario logueado--->

                        Estas conectado como: {{ user.get_username }} <!----- tus permisos son:{ { perms.app_name } } -->

                        {% if not perms.sitio.delete_producto %}  <!---Usuario Comun---> 
                            <a role="button" class="btn btn-outline-success btn-sm" href="{% url 'sitio:consultar_carrito' %}">Carrito</a>
                        {% endif %} 

                        <a role="button" class="btn btn-outline-warning btn-sm" href="{% url 'logout' %}?next={{request.path}}">Salir</a>

                    {% else %}      <!--usuario NO logueado- "{% url 'sitio:producto_alta' %}"-->

                        <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'login' %}?next={{request.path}}">Login</a>
                        <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'usuarios:registrarse' %}?next={{request.path}}">Registro</a>
                        <a role="button" class="btn btn-outline-primary btn-sm" href="{% url 'login' %}?next={{request.path}}">Carrito</a>
               
                    {% endif %} 

                </div>
                <a class="nombre" href="{% url 'sitio:index' %}"><img class="logo" src="{% static 'img/logo_azul.png' %}" alt="Desarrollo Web">
                </a>
            </header>

            <nav id="menu_principal" class="navbar navbar-expand-lg navbar-light bg-light">
                  <!--<a class="navbar-brand" href=""><i class="fas fa-globe"></i></a>-->
                  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <!---
                  --->
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    
                    <ul class="navbar-nav mr-auto">
                    
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'sitio:index' %}">Home <span class="sr-only">(current)</span></a>
                      </li>
                     
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Categorias
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for categoria in lista_categorias %}
                                <a class="dropdown-item" href="{% url 'sitio:filtro_categorias' categoria.id%}">{{ categoria }}</a>
                            {% endfor %}
                        </div>
                      </li>
                       <!----->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'sitio:about' %}">
                                Acerca de...
                            </a>
                        </li>
                       <li class="nav-item">
                            <a class="nav-link" href="{% url 'sitio:contact' %}">
                                Contacto
                            </a>
                        </li>
                        {% if perms.sitio.delete_producto %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'sitio:producto_alta' %}">
                                    Nuevo producto
                                </a>
                            </li> 
                        {% endif %} 

                    </ul>
                    <form action="{% url 'sitio:filtro_productos' %}" method="get"class="form-inline my-2 my-lg-0">
                      <input class="form-control mr-sm-2" type="search" placeholder="Buscar" name= "busqueda" aria-label="Search" value = "{{ request.GET.busqueda }}">
                      <button class="btn btn-outline-primary" type="submit">IR</button>
                    </form>
                  </div>
                </nav>

<!--<form action="{ % url 'sitio:filtro_articulos' % }" method="get"> 
             <div>
                    <span><input type="search" size="18" aling= "justify-content-center" name="busqueda" placeholder="Buscar" value = "{ { request.GET.busqueda } }"></span>
                    <button type="submit" class="btn btn-outline-secondary btn-sm">IR</button>
            </div>
</form>-->

             <!-------------->
            {% block content %}
            {% endblock %}
        </div>
    </body>
    <!--Pie de pagina -->
    <footer>
        <div class="container">
            <div class="row redes-sociales justify-content-center">
                <div class="col-auto">
                    <a href="#" class="icono icon-facebook facebook"></a>
                    <a href="#" class="icono icon-twitter twitter"></a>
                    <a href="#" class="icono icon-instagram instagram"></a>
                </div>
                <div class="col-12 text-center copyright">
                    <samp>
                        <br>
                        <p>Jaguarete KAA S.A.</p>
                    </samp>
                    <samp>
                        <p>Copyright &copy; 2021 · Elkin Eduardo Bedoya Muñoz (Diseñador Web) </p>
                    </samp>
                </div>
            </div>

        </div>
    </footer>
<!---------------------------------->
    <div class="footer">
    <div class="container">
        <div class="row ">
            <div class="col-12 in-line d-flex justify-content-center">
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-google-plus-g"></i>
                    <i class="fab fa-whatsapp"></i>
                    <i class="fas fa-globe"></i>
            </div>
        </div>
        <!---<div class="row">
            <div class="col-12 d-flex justify-content-center icons">
                <nav class="navbar navbar-expand-sm navbar-sucess my-navbar">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                             <strong>
                                      <ul class="navbar-nav">
                                                <li class="nav-item active">
                                                  <a class="nav-link" href="#"><p>Home</p></a>
                                                </li>
                                                <li class="nav-item">
                                                  <a class="nav-link" href="#">My gifts</a>
                                                </li>
                                                <li class="nav-item">
                                                  <a class="nav-link" href="#">Contact</a>
                                                </li>
                                                <li class="nav-item">
                                                  <a class="nav-link" href="#">Register</a>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link" href="#">Login </a>
                                                </li>
                                         </ul>
                              </strong>
                         </div>
                </nav>
            </div>
        </div> --->
       
        <div class="row">
            <div class="col-12 ">
                <br>
                 <p class="text-center">Cursos Polotic Misiones - Argentina.</p>
            </div>
        </div>

    </div>
</div>

<!---------------------------------->
</html>